### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by caugner** [patrick330602/termuxer#1]
It looks like the theme doesn't work out of the box, but needs additional `pkg`s installed. 

After switching to the `termuxer` theme, I'm getting the following errors after starting Termux:

```
No command '404:' found, did you mean:
 Command 'lz4c' from package 'lz4'
 Command 'lz4' from package 'lz4'
 Command 'm4' from package 'm4'
```

**Comment by patrick330602** [comment]
Never realized some people would still use this theme... I have been given up this project for a long time, but here is a possible solution:
0. remove the old theme if exists;
1. Install `Termux API` from android store;
2. Set up oh-my-zsh using [4679/oh-my-termux](https://github.com/4679/oh-my-termux);
3. Download them using:
 ```
curl -fsSL https://raw.githubusercontent.com/patrick330602/termuxer/master/termuxer.zsh-theme >> ~/.oh-my-zsh/custom/themes/termuxer.zsh-theme
```

I will change the README later... haven't touch this piece of project for some time

**Comment by rabate118** [comment]
`curl -fsSL https://raw.githubusercontent.com/patrick330602/termuxer/master/termuxer.zsh-theme >> ~/.oh-my-zsh/custom/themes/termuxer.zsh-theme`
